---
title: "Web_scraping"
format: html
editor: visual
execute: 
  echo: true
  error: true
  warning: true
  message: true
---

# Importez depuis le web

(https://www.keringfoundation.org/fr/articles/d'egal-a-egale/)

```{r}
install.packages("rvest")
library(rvest)
```

```{r}
stereotype_genre <- read_html("https://www.keringfoundation.org/fr/articles/d'egal-a-egale/") |>
html_elements("ul") |>
html_text()
stereotype_genre_chiffres_cles <- stereotype_genre[2]
```

```{r}
install.packages(stringr)
library(stringr)
# séparation des phrases avec le séparateur \\. et simplify = TRUE pour que les phrases apparaissent séparées
stereotype_genre_chiffres_cles_phrases <-
str_split(
stereotype_genre_chiffres_cles,
"\\.",
simplify = TRUE
)

# extraction de nombres et des mots garcon et fille
str_c(
stereotype_genre_chiffres_cles_phrases |>
str_extract(pattern = "[:digit:]+%"),
stereotype_genre_chiffres_cles_phrases |>
str_to_lower() |>
str_extract(pattern = "fille|garçon"),
sep = " "
)

# concatenation des données et les NA prennent le dessus sur les autres, il faut donc les remplacer par rien

str_c(
stereotype_genre_chiffres_cles_phrases |>
str_extract(pattern = "[:digit:]+%") |>
str_replace_na(""),
stereotype_genre_chiffres_cles_phrases |>
str_to_lower() |>
str_extract(pattern = "fille|garçon") |>
str_replace_na(""),
sep = " "
)

```

```{r}
install.packages("magick")
library(magick)
```
```{r}
logo_oc <- image_read("https://user.oc-static.com/upload/2023/10/13/16972008380354_OC-Course-Banners_A-vous-de-jouer%20%20%281%29.png")
logo_oc <- logo_oc_jpg <- image_convert(logo_oc, format = "jpg")
centre_logo_oc <- image_crop(logo_oc_jpg, "350X350+25+25")
centre_logo_oc
```
